### ISSUE TITLE
bug in kernel sampling?

### ISSUE THREAD

**Issue by nilsbecker** [igarnier/prbnmcn-dagger#13]
https://github.com/igarnier/prbnmcn-dagger/blob/93d5f0bb58d83ba62f3659d8470c43993f482f29/src/smc_inference.ml#L698

here, iiuc, when asking a kernel distribution to generate a new sample, one always starts from the fixed initial condition of the kernel and takes a single step, instead of actually keeping a current step as mutable state and thereby generating a markov chain on successive calls.

the current behavior appears to be wrong? happy to be corrected!

**Comment by igarnier** [comment]
I believe you're right. I think I didn't implement a stateful variant of the kernel because I could not see how to easily index the state of the kernel by particles - a naive implementation would let all particles share the same state, which would introduce bias. We probably need to maintain for each `_ Dist.t` of `kernel` kind a table mapping particles to the kernel state, and make sure that upon resampling, this state is not shared across cloned particles but properly duplicated.

**Comment by igarnier** [comment]
Kernels were removed from SMC inference in 0.0.5
