### ISSUE TITLE
Inaccurate documentation in resampling module

### ISSUE THREAD

**Issue by igarnier** [igarnier/prbnmcn-dagger#3]
Feedback from @nilsbecker

one thing that was not clear to me initially was that after a resampling, all of the weights are in fact always equal to 1 -- this is not strictly required i think, one could also think of resampling schemes that make weights only approximately equal. so that could be stated explicitly

https://github.com/igarnier/prbnmcn-dagger/blob/360e196be3e28cbcc67691a1fd68f1cd93743e35/src/resampling.mli#L23 
this scheme appears to make sense only if the weights are already normalized to sum to 1. in the implementation, the returned weights sum to the number of particles as far as i could see.

also, the U_i are N-1 in total, so the sum over r_k is only N-1 which is probably not intended? (unless i'm mistaken). nitpicking, to avoid double counting in edge cases, the intervals [W_{k-1}, W_k] should probably be half-open.

https://github.com/igarnier/prbnmcn-dagger/blob/360e196be3e28cbcc67691a1fd68f1cd93743e35/src/resampling.mli#L36
in this line, intervals are discussed but for the following resampling rule, it seems only the points (i-1)/N + U_i are of interest, not those intervals.

_Originally posted by @nilsbecker in https://github.com/igarnier/prbnmcn-dagger/issues/2#issuecomment-1609375530_

**Comment by igarnier** [comment]
@nilsbecker  Following a rather deep refactor of the sequential Monte Carlo inference, I tried to improve the related part of the doc.
- Documentation for the main module: http://stengah.free.fr/doc/prbnmcn-dagger/Dagger/Smc_inference/index.html
- Documentation for resampling: http://stengah.free.fr/doc/prbnmcn-dagger/Dagger/Resampling/index.html
- A page with a few examples http://stengah.free.fr/doc/prbnmcn-dagger/smc_inference_example.html

Any feedback would be appreciated!

**Comment by nilsbecker** [comment]
Reading the main module docs, 

- i appreciate the general intro including nice illustration. great!
- typo: 'thie'
- i first got stuck on the term 'particle output' -- i would have used 'current value' or so. but it's ok after rereading
- 'resampling state' is not explained when used first
- the docs of `Resampling_types_S` and `Make` don't explain the purpose and usage of `resampling_state` either. here i'm still confused what it is good for. also looking at `Float_smc` shows that `resampling_state` is `unit` which makes me think it's something that's not usually needed? but still wondering what it does.

[edit] I just now also descended into the `Smc_inference.S` docs. For the `run` function I wondered if it wouldn't be cleaner to separate the preparation of the initial population from propagating a population. i.e. an `init_pop` function which would by default trivially make `npart` samples with equal weight. and then an `continue_run` function which maps weighted population to weighted population. that way one could start with an arbitrarily weighted initial population if desired. also, in the doc of `run`, the prototype function call seems to be missing an argument compared to the signature.

**Comment by nilsbecker** [comment]
Reading the resampling docs. 

First of all, it's a cool improvement that users can now implement their own resampling strategy. 

- 'sampling N new particles from a given _weighted_ population...'
- what's the main disadvantage or multinomial resampling? would it make sense to offer that as well simply because it is the most straightforward option?
- no need to bullet list the two strategies and then have a separate paragraph for each. you could just retain the detailed paragraphs only.
- The outcome of resampling ... all with equal weight' sounds like this is a general requirement for any resampling scheme, also the custom ones. This sounds like an unnecessary restriction. Or is the wording just ambiguous?
- how about this: 'Consider the set of points  U_i = U + ... for i=1...N-1. Associate to each particle its cumulative _normalized_ weight W_k = (w_1 + ... + w_k)/W and set W_0 = 0'
- In the stratified resampling, again the intervals seem to be unnecessary / confusing. one could just talk about the points (i-1)/N + U_i . These are the only thing that's needed to get r_k. No?
- A link for the reference would be good.

About the strategy interface:

- i understand that the particle type should not leak into the resampling strategy. is the first-class module the standard way to obtain that? how would a pure functor version look, out of curiosity? would `Strategy` need to become a functor? How can one make `Environment` generic so that it can be the input signature for that functor?
- maybe it's really easiest the way it is...
- inside of `Environment`: would a `fold` function on the population not be nice in addition to `iter`, or is there a reason against it?
- i could think of resampling strategies that do not strictly conserve the population size. is that allowed?
- it seems that the built in strategies now contain an effective sample size threshold -- does this mean they to ess estimation? if so, this does not appear to be documented. also, afaik there are various ways of estimating ess and a user will likely want to choose / implement their own.

**Comment by nilsbecker** [comment]
Reading the examples docs

- in the code examples it's not clear what modules need to be opened for the code to work
- the first example 
    - again uses a `unit` resampling state so i'm still wondering what it's good for...
    - i wonder if the `run` function could use labeled arguments? i'm usually not a fan of those but for a big wrapper    function that gets called not so often it might be worth considering
    - it was not immediately clear that `pop.yielded = 0` means all particles have terminated. maybe `yielded` could be called `active` or something like that? not sure.
    - `pop.total_mass` is the mass of all non-terminated particles -- is including the terminated ones nonsense? otherwise it could be called `active_mass`? again, not sure.
    - the figure is nice! it would be nice to say what initial number of the sequence if fitted polynomials is shown in words (15 i think)

**Comment by igarnier** [comment]
Thanks a lot for the extensive feedback!

> typo: 'thie'
- fixed

> i first got stuck on the term 'particle output' -- i would have used 'current value' or so. but it's ok after rereading_
- Left as is for now. For a model of type `'a t` I would expect the value of a particle to be the one it evaluates to (of type `'a`) when it is terminated rather than the one given to `yield`.

> 'resampling state' is not explained when used first
- I tried to improve the explanation around `resampling_state`, see http://stengah.free.fr/doc/prbnmcn-dagger/Dagger/Smc_inference/index.html

> For the run function I wondered if it wouldn't be cleaner to separate the preparation of the initial population from propagating a population.
- For now I added a `run_custom` function alongside `run` which allows to specify a family of weighted models for the initial population. It'd be nice to have something along the lines you suggest, e.g. a function `next : 'a state -> ('a population * 'a state) option instead of having through a `Seq.t`  but it seems non-trivial.

> also, in the doc of run, the prototype function call seems to be missing an argument compared to the signature.
- fixed

> 'sampling N new particles from a given weighted population...'
- applied

> what's the main disadvantage or multinomial resampling? would it make sense to offer that as well simply because it is the most straightforward option?
- IIUC it introduces more variance in the random variable corresponding to the replication counts (see Doucet&Johansen 3.4). TBH the only reason why I don't include it is that it would require adding another dependency to the library (for the alias sampler), which I'd like to avoid. I have no practical experience with multinomial resampling, if you think it's a must-have then I'll carve out the required piece of code to have it in `dagger`

> no need to bullet list the two strategies and then have a separate paragraph for each. you could just retain the detailed paragraphs only.
- fixed

> The outcome of resampling ... all with equal weight' sounds like this is a general requirement for any resampling scheme, also the custom ones. This sounds like an unnecessary restriction. Or is the wording just ambiguous?
> 'Consider the set of points U_i = U + ... for i=1...N-1. Associate to each particle its cumulative normalized weight W_k = (w_1 + ... + w_k)/W and set W_0 = 0'
> In the stratified resampling, again the intervals seem to be unnecessary / confusing. one could just talk about the points (i-1)/N + U_i . These are the only thing that's needed to get r_k. No?
> A link for the reference would be good.
- I moved the description of the stratified and systematic resampling algorithms to the `Make_predefined` functor. It should make it clearer what is required of resampling algorithms in general and what is specific to those in `Make_predefined`.
- I simplified the descriptions of the algorithms by removing references to the intervals
- Reference added

> I understand that the particle type should not leak into the resampling strategy. Is the first-class module the standard way to obtain that? How would a pure functor version look, out of curiosity? would Strategy need to become a functor? How can one make Environment generic so that it can be the input signature for that functor? Maybe it's really easiest the way it is...
- There are probably ways to get rid of the 1st class module. For instance:
  - we could add an `Environment` module implementing the `Resampling.Environment` signature in `Smc_inference` and let the `Smc_inference.Make` functor take an additional parameter corresponding to the strategy; the drawback would be that one would need to re-instantiate the functor for each resampling strategy
  - instead of manipulating directly the population through an environment, the resampling strategy could produce an explicit list of "effects" represented as e.g. elements of an ADT, the list would then be given a concrete semantics by the inference algorithm; this would be at the cost of additional allocations to represent the "effects"
  - or we could declare actual effects as introduced by OCaml 5 and let the inference algorithm handle them

> inside of Environment: would a fold function on the population not be nice in addition to iter, or is there a reason against it?
- added a `fold`

> I could think of resampling strategies that do not strictly conserve the population size. is that allowed?
- yes, absolutely!

> It seems that the built in strategies now contain an effective sample size threshold -- does this mean they do ess estimation? If so, this does not appear to be documented. Also, afaik there are various ways of estimating ess and a user will likely want to choose / implement their own.
- Yes, the algorithm performs ESS estimation using the formula in Doucet&Johansen. I added some documentation on the subject. Note that nothing prevents users to implement alternate ESS estimation techniques in their custom resampling strategies. Since the inference algorithm already performs a run over the particles before resampling to rescale their weight (divide by the maximum weight basically) we take advantage of this iteration to also compute various metrics such as the total mass and the sum of squared weights, which we use to compute ESS.

> in the code examples it's not clear what modules need to be opened for the code to work
- added the missing open

> the first example again uses a unit resampling state so i'm still wondering what it's good for...
- let me know if the added documentation is not enough. For the record I needed this feature to implement the abc sampling technique I mentioned in the other issue. For instance the score of a particle a given step might depend on some values computed during the last resampling.

> i wonder if the run function could use labeled arguments? i'm usually not a fan of those but for a big wrapper function that gets called not so often it might be worth considering
- I added a label to the integer argument, I think the other types indicate clearly enough the purpose of the argument

> it was not immediately clear that pop.yielded = 0 means all particles have terminated. maybe yielded could be called active or something like that? not sure.
- renamed to `active`

> pop.total_mass is the mass of all non-terminated particles -- is including the terminated ones nonsense? otherwise it could be called active_mass? again, not sure.
- `pop.total_mass` is the mass of all particles, terminated and active

> the figure is nice! it would be nice to say what initial number of the sequence if fitted polynomials is shown in words (15 i think)
- added a few words to say that indeed, these plots are a subset of 15 of mean polynomials

**Comment by nilsbecker** [comment]
> > 'resampling state' is not explained when used first
> 
>     * I tried to improve the explanation around `resampling_state`, see http://stengah.free.fr/doc/prbnmcn-dagger/Dagger/Smc_inference/index.html

the new explanation is helpful! is the following somewhat more verbose version a correct understanding?

  - Particles give their current value as argument to [yield](http://stengah.free.fr/doc/prbnmcn-dagger/Dagger/Smc_inference/module-type-S/index.html#val-yield). A resampling step uses these values from all currently active patricles to resample and reassign weights. The outcome (of type resampling_state) is also broadcast back to each active particle as the value to which [yield](http://stengah.free.fr/doc/prbnmcn-dagger/Dagger/Smc_inference/module-type-S/index.html#val-yield) has evaluated.
  - [Resampling steps](http://stengah.free.fr/doc/prbnmcn-dagger/Dagger/Resampling/index.html#type-strategy) also take the previous resampling outcome as an additional argument. In many cases the strategy does not require to maintain state across steps, and one can set `resampling_state = unit`.


> > what's the main disadvantage or multinomial resampling? would it make sense to offer that as well simply because it is the most straightforward option?
> 
>     * IIUC it introduces more variance in the random variable corresponding to the replication counts (see Doucet&Johansen 3.4). TBH the only reason why I don't include it is that it would require adding another dependency to the library (for the alias sampler), which I'd like to avoid. I have no practical experience with multinomial resampling, if you think it's a must-have then I'll carve out the required piece of code to have it in `dagger`

I see, i did not realize that would add a dependency. Makes sense to avoid it.


> > 'Consider the set of points U_i = U + ... for i=1...N-1. Associate to each particle its cumulative normalized weight W_k = (w_1 + ... + w_k)/W and set W_0 = 0'

I believe the normalization of the W_k by W is still missing in the new version? (the w_k add up to W). Otherwise I like the changes!

> 
> 
> > I understand that the particle type should not leak into the resampling strategy. Is the first-class module the standard way to obtain that? How would a pure functor version look, out of curiosity? would Strategy need to become a functor? How can one make Environment generic so that it can be the input signature for that functor? Maybe it's really easiest the way it is...
> 
>     * There are probably ways to get rid of the 1st class module. For instance:
>       
>       * we could add an `Environment` module implementing the `Resampling.Environment` signature in `Smc_inference` and let the `Smc_inference.Make` functor take an additional parameter corresponding to the strategy; the drawback would be that one would need to re-instantiate the functor for each resampling strategy
>       * instead of manipulating directly the population through an environment, the resampling strategy could produce an explicit list of "effects" represented as e.g. elements of an ADT, the list would then be given a concrete semantics by the inference algorithm; this would be at the cost of additional allocations to represent the "effects"
>       * or we could declare actual effects as introduced by OCaml 5 and let the inference algorithm handle them

Using OCaml 5 Effects sounds cool but might be a bit premature, given that they are supposed to become typed at some point? The first option sound the most standard to me. The second is a bit unclear to me -- what would be an example of such an effect?

Overall I think the option that's most straightforward for the user would be a good option. Not sure which one that is. I think when keeping the current way of doing things, either functors with strategy modules or first class modules with strategy values may be similar in complexity. Functors feel  a bit more 'standard' to me, given that the `Environment` is already a module that must be provided. But either option seems fine.

> 
>     * Yes, the algorithm performs ESS estimation using the formula in Doucet&Johansen. I added some documentation on the subject. Note that nothing prevents users to implement alternate ESS estimation techniques in their custom resampling strategies. Since the inference algorithm already performs a run over the particles before resampling to rescale their weight (divide by the maximum weight basically) we take advantage of this iteration to also compute various metrics such as the total mass and the sum of squared weights, which we use to compute ESS.

ok, good! i'm confused about one point: is there a standard implementation of the `Environment` module type exposed to the user for making a custom strategy? (e.g. to use the variance based ESS estimator) I only found the module type in the docs, not a module.


>     * let me know if the added documentation is not enough. For the record I needed this feature to implement the abc sampling technique I mentioned in the other issue. For instance the score of a particle a given step might depend on some values computed during the last resampling.

docs look good. 

> 
> > i wonder if the run function could use labeled arguments? i'm usually not a fan of those but for a big wrapper function that gets called not so often it might be worth considering
> 
>     * I added a label to the integer argument, I think the other types indicate clearly enough the purpose of the argument
> 
> 
> > it was not immediately clear that pop.yielded = 0 means all particles have terminated. maybe yielded could be called active or something like that? not sure.
> 
>     * renamed to `active`
> 
> 
> > pop.total_mass is the mass of all non-terminated particles -- is including the terminated ones nonsense? otherwise it could be called active_mass? again, not sure.
> 
>     * `pop.total_mass` is the mass of all particles, terminated and active

but Env.total is the mass of the active ones, yes? as long as it's clearly documented, fine.

i'll have a look at the abc example as well -- hopefully everything that i'd need for my indended ABC use is already there ;)

**Comment by igarnier** [comment]
> the new explanation is helpful! is the following somewhat more verbose version a correct understanding?

yes!

> I believe the normalization of the W_k by W is still missing in the new version? (the w_k add up to W). Otherwise I like the changes!

indeed, fixed

> Using OCaml 5 Effects sounds cool but might be a bit premature [...]

I agree that it's a very bad idea to directly expose effects to users right now, as the feature is still flagged as experimental. Perhaps there's place to design an API that hides them under a safe abstraction.

> The second is a bit unclear to me -- what would be an example of such an effect?

I should not have mentioned effects for that one, sorry. I think it would boil down to defining a small DSL for resampling as an ADT, users would describe their resampling strategy as a term in that DSL which would be interpreted by the inference algorithm. 

> ok, good! i'm confused about one point: is there a standard implementation of the Environment module type exposed to the user for making a custom strategy? (e.g. to use the variance based ESS estimator) I only found the module type in the docs, not a module.

There is one canonical implementation of the `Environment` module, hidden to the user. To be precise: it is a first-class module instantiated on each resampling. 

> but Env.total is the mass of the active ones, yes? as long as it's clearly documented, fine.

No, `Env.total` is the total mass of the population, active + terminated. Note that terminated particles do continue to participate in resamplings (and they may not survive). The rationale is that from the point of view of inference, whether a particle has terminated its execution or not is not relevant.
Do you find this surprising?

**Comment by nilsbecker** [comment]
> > ok, good! i'm confused about one point: is there a standard implementation of the Environment module type exposed to the user for making a custom strategy? (e.g. to use the variance based ESS estimator) I only found the module type in the docs, not a module.
> 
> There is one canonical implementation of the `Environment` module, hidden to the user. To be precise: it is a first-class module instantiated on each resampling.

i was thinking it could make sense to make the standard ess function available to users that would like to do a custom resampling, as a convenience? 

[edit]: i think i misunderstood. it seems that the `Environment` including the standard ess function is indeed provided when running a strategy within `Smc.run`. for some reason i thought the user would need to implement their own `Environment`.

> No, `Env.total` is the total mass of the population, active + terminated. Note that terminated particles do continue to participate in resamplings (and they may not survive). The rationale is that from the point of view of inference, whether a particle has terminated its execution or not is not relevant. Do you find this surprising?

i haven't thought about it much to be honest. can terminated particles still get mutated at some of the primitives along the way? that would make sense -- i had not considered this before.

**Comment by igarnier** [comment]
> i was thinking it could make sense to make the standard ess function available to users that would like to do a custom resampling, as a convenience?

I should clarify my statement about this implementation being hidden to the user: upon resampling, a first class module of type `Environment` is instantiated and is passed as an argument to the strategy. Any user-implemented resampling strategy will be passed this first class module: see the second argument of http://stengah.free.fr/doc/prbnmcn-dagger/Dagger/Resampling/index.html#type-strategy). Last, this implementation does make available the standard `ess` function: http://stengah.free.fr/doc/prbnmcn-dagger/Dagger/Resampling/module-type-Environment/index.html#val-ess
For instance it is used in the multinomial resampling example, cf http://stengah.free.fr/doc/prbnmcn-dagger/smc_inference_example.html#example:-multinomial-resampling

>  haven't thought about it much to be honest. 

The problem arises with models such as the following, where the number of `yield`s encountered by each particle is random:
```ocaml
let rec loop n acc =
  if n = 0 then
   return acc
  else
   let* b = sample @@ bernoulli ~bias:0.5 in
   if b then
    let* () = yield () in
    loop (n - 1) (b :: acc)
   else
    loop (n - 1) (b :: acc)
```
What semantics should we give? Intuitively, `yield` should not affect the final distribution of booleans in the list. 

> can terminated particles still get mutated at some of the primitives along the way? that would make sense -- i had not considered this before.

In the current implementation, a particle which is terminated doesn't change value. Resampling can only either carry it forward to the next generation (possibly changing its weight) or drop it.

**Comment by nilsbecker** [comment]
> Last, this implementation does make available the standard `ess` function:

yes, i also now figured that out, thanks (see edit above)

in the example you gave i can see that the number of `yield`s is random. so in a population of, say, 10 particles each with `n`=8 it could happen that, e.g., in the third resampling step two of the particles already terminated because their values of `b` do not make them encounter any more `yield`s along the way. ok. smc resampling will now resample from the full population according to their weights (which are trivial in this example). this appears reasonable to me. it appears unreasonable to exclude the terminated ones.

i think i was mixing this up with the single-site mh sampling strategy, which does not have `yield`. one can think of a somewhat similar example:
```ocaml
let rec loop n acc = 
  if n = 0 then return acc
  else
    let* b = sample @@ bernoulli ~bias:0.1 in
    if b then return acc
    else 
      let* _ = score 10. in
      loop (n - 1) (() :: acc)
```
which should generate `unit list`s with a uniform length distribution due to cancellation of sampling and scoring i think. here i would expect a mh update to select a sampling event anywhere along the history of the loop, which is then rerun until done.

anyway, what would be the easiest way for me to git pull a current dev version of dagger to test further? i would like to give a version of abc-smc a go...

**Comment by igarnier** [comment]
> anyway, what would be the easiest way for me to git pull a current dev version of dagger to test further? i would like to give a version of abc-smc a go...

You can clone https://gitlab.com/igarnier/monorepo/ and `dune build` in the `dagger` subdirectory. For the abc example, `cd examples/smc-abc` and `dune exec ./abc.exe` should produce some plots.

Otherwise, I'm going to cut a release soon (as soon as https://github.com/ocaml/opam-repository/pull/24126 gets merged).

**Comment by nilsbecker** [comment]
Thanks! In view of the release, some nitpicks about `Environment`:

  - the name may be too generic. `Particles` would work for instance? `Population`?
  - `score` could be called `get_score` to accompany `get` and avoid confusion with `score` of a strategy.
  - `get` could be called `get_output`
  - the docs should decide for either 'score' or 'weight'
  - I was also thinking it would make sense to always bundle output and weight together. but i see now that when a particle has terminated then only the weight is available, so that probably isn't going to be feasible.
  - to be analogous to `Array.fold` and `Seq.fold`, the type of `fold` would need to take a function that takes the accumulator first, so: `(acc -> p -> r -> acc) -> acc -> acc`

**Comment by nilsbecker** [comment]
> You can clone https://gitlab.com/igarnier/monorepo/ and `dune build` in the `dagger` subdirectory. For the abc example, `cd examples/smc-abc` and `dune exec ./abc.exe` should produce some plots.
> 
> Otherwise, I'm going to cut a release soon (as soon as [ocaml/opam-repository#24126](https://github.com/ocaml/opam-repository/pull/24126) gets merged).

i was able to pull the monorepo, but the current version builds only with ocaml 5 -- will this be a requirement? (that's fine, i personally would want to hold off until 5.1 to switch though)

**Comment by igarnier** [comment]
Yes, I'm using effects internally to perform a type-safe inversion of control so switching to OCaml >= 5.0 will be a requirement.

**Comment by igarnier** [comment]
> Thanks! In view of the release, some nitpicks about `Environment`:
> 
>     * the name may be too generic. `Particles` would work for instance? `Population`?
> 
>     * `score` could be called `get_score` to accompany `get` and avoid confusion with `score` of a strategy.
> 
>     * `get` could be called `get_output`
> 
>     * the docs should decide for either 'score' or 'weight'
> 
>     * I was also thinking it would make sense to always bundle output and weight together. but i see now that when a particle has terminated then only the weight is available, so that probably isn't going to be feasible.
> 
>     * to be analogous to `Array.fold` and `Seq.fold`, the type of `fold` would need to take a function that takes the accumulator first, so: `(acc -> p -> r -> acc) -> acc -> acc`

Fixed, except for "bundle output and weight together" for the exact reason you give. Thanks!
